### PR TITLE
New attribute to invalidate cache for a particular resource

### PR DESCRIPTION
**Pull request by jbernalvallejo**
# What

Be able to remove the cache for a particular resource in our cache store. 

Example:

```
GET .../api/prices/product1?country=GB
GET .../api/prices/product1?country=US
GET .../api/prices/product2?country=US
GET .../api/prices/product3?country=US

// we want to invalidate all the cache for product1, but not for product2 or product3 when
PUT/PATCH/DELETE  .../api/price/product1
```
# Why

Currently, in our work we are holding cache for more then 50.000 resources for an endpoint. At this moment with the different existing attributes for invalidating cache in this library we can only remove the whole catalog. For us, this means we are wiping out a massive amount of valid cached data. 
## Why not doing it manually inside the controller action

We really care about Separation of Concerns in our apps and we do think our controllers should not be responsible for worrying about caching.
# How
## Finding out how to address the solution

After taking a look at the CacheOutputAttribute implementation, we have seen that for every new entry in the cache store, we are saving three keys per resource: etag, content-type and the response itself. 

These three entries have something in common: they all start by the same prefix given by the MakeCacheKey method. 

Given this, what we thought is we could try to find a way to remove these three entries when the resource is modified (PUT/PATCH) o removed (DELETE).

_Note: Obviously, we don't need to do anything for POST since it is a new resource other than just invalidate the cache for the GET ALL endpoint -currently supported with existing attributes._

With this in mind, we saw we could not use at all the existing MakeCacheKey to guess the prefix for the entries to delete, since it is an interface that any user of this library can implement in his own way. Even it might contain information about the _query string_ or the _media type_ as currently happens with the default implementation.  However, for instance we would like to remove cache entries for a resource no matter the media type. Otherwise, we might end up returning right data for JSON but wrong for XML or any other format.
## Proposed solution

The idea is to provide a new attribute over your controller where you can pass a class responsible for getting this prefix. 

The prefix generator class must implement the following interface:

``` csharp
public interface IKeyPrefixGenerator
{
  string Generate(HttpActionContext actionContext, string baseCacheKey);
}
```

_NOTE: The reason to pass the previous parameters to this method is to provide some objects that might be useful to the developer in order to generate the needed prefix. They are:_
- _actionContext: through this object, controller, name and arguments of the current action are accessible._
- _baseCacheKey: base cache key for the ActionName provided to the attribute_

The generated prefix will be used by the attribute to get every entry which matches it and remove them. For this behaviour we've added a new method in the interface IApiOutputCache

``` csharp
IEnumerable<string> FindKeysStartingWith(string prefix);
```

_Note: We decided not to use the existing AllKeys since depending on the chosen cache provider (redis, mongodb) it might mean loading thousands on entries in memory which might break the application server_.

So the important part of the attribute is:

``` csharp
var prefix = _keyPrefixPrefixGenerator.Generate(httpActionContext, baseCacheKey);
var keys = WebApiCache.FindKeysStartingWith(prefix);
foreach (var key in keys)
{
  WebApiCache.Remove(key);
}
```

Having all this, the way to make it work on your controller is:

``` csharp
// Invalidates the cache of the resource /api/controller/id
[InvalidateCacheOutputByPrefixKey(typeof(KeyPrefixGenerator), "Get")]
public void Put(PutObject putObject)
{
    // updating resource
}
```

As you can see, to keep everything aligned with your current implementation we support the creation of the attribute with the method name and even the controller type. 
# Example

``` csharp
// Controller
[CacheOutput(ClientTimeSpan = 100, ServerTimeSpan = 100)]
public void Get(string id)
{
    // ...
}

// Invalidates the cache of the resource /api/controller/id
[InvalidateCacheOutputByPrefixKey(typeof(KeyPrefixGenerator), "Get")]
public void Put(PutObject putObject)
{
    // ...
}

...

// KeyPrefixGenerator
public class KeyPrefixGenerator : IKeyPrefixGenerator
{
    public string Generate(HttpActionContext actionContext, string baseCacheKey)
    {
        var resourceId = actionContext.ActionArguments.FirstOrDefault(pair => pair.Key == "Code").Value;
        return baseCacheKey + "-resourceid=" + resourceId;
    }
}    
```
# Comments
- Implementation for memory cache and unit test for FindKeysStartingWith are included.
- Unit test for the attribute is included.
- All this change has been done by @jordiCabeza and me.
- Sorry for the long text :smile:

### CODE REVIEW

**Comment by OleCordsen** [comment]
We need this feature too, would be really great if it could be merged.

**Comment by TheFastCat** [comment]
I would also like this functionality

**Comment by jesulink2514** [comment]
Have you tested this implementation with concurrency? Don't you need to lock the Cache object while you're iterating over it?

**Comment by jbernalvallejo** [comment]
This has been ignored for more than two years now. Closing it.

**Comment by johnib** [comment]
I have replicated this repo due to this need.
This feature was implemented on my library few days ago and it is under PR.
It will be pushed to my repo in a week.

you're welcome to follow
https://github.com/johnib/WebAPI.CacheResponse


* gave the credit to filip for his inspiration

**Pull request closed without merging**
